import type { Metadata } from "next";
import "./globals.css";

import { Header } from "@/app/header";
import { Footer } from "@/app/footer";

import { AOSInit } from "@/app/aos";
import "aos/dist/aos.css";

import { ebGaramond } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Shore Guesthouse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.className} antialiased flex flex-col min-h-screen`}
      >
        <AOSInit />
        <Header />
        <main className="grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
