import type { Metadata } from "next";
import { EB_Garamond, Roboto } from "next/font/google";
import "./globals.css";
// import { Header } from "@/app/header";
// import { Footer } from "@/app/footer";

import "aos/dist/aos.css";
// import { AOSInit } from "./aos";

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
});

export const roboto = Roboto({
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Shore Guesthouse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
